name: Il mio primo github action
on: 
  push: 
jobs: 
  italian-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4  
      - run: ls
      - run: pwd
      - run: ls -la  
      - run: java -version
      - run: ls
      - run: pwd 
        working-directory: DatabaseFilm 
      - run: mvn install -DskipTests
        working-directory: DatabaseFilm 
      - run: mvn test
        working-directory: DatabaseFilm 
